"""
Ghi OPENROUTER_API_KEY từ file .env vào cham_bai/_embedded_key.py để PyInstaller đóng gói vào EXE.
Chạy trước khi build: python scripts/embed_key_from_env.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from dotenv import dotenv_values


def main() -> int:
    env_path = ROOT / ".env"
    vals = dotenv_values(env_path) if env_path.is_file() else {}
    key = (vals.get("OPENROUTER_API_KEY") or "").strip()

    out = ROOT / "cham_bai" / "_embedded_key.py"
    body = (
        "# AUTO-GENERATED by scripts/embed_key_from_env.py — do not commit real keys.\n"
        "OPENROUTER_API_KEY_EMBEDDED = "
        + repr(key)
        + "\n"
    )
    out.write_text(body, encoding="utf-8")
    if key:
        print(f"Embedded key -> {out} ({len(key)} chars). Do not commit real keys.")
        print("Tip: git checkout cham_bai/_embedded_key.py")
    else:
        print(f"Wrote empty key -> {out} (no OPENROUTER_API_KEY in .env).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
